name: Build

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tawk.to'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Publish to npm
        run: |
          npm publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
